name: Tests
on:
  pull_request_target:
  push:
    branches:
      - main

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - run: npm ci && npm run build
    - run: npm test
